### ISSUE TITLE
Create redirect strategy for altheamesh.com -> althea.org

### ISSUE THREAD

**Issue by jtremback** [althea-net/issue-warehouse#12]
- Redirect equivalent pages, i.e. /whitepaper -> /whitepaper
- Check internal pages of existing site and ask Jehan about any ambiguities
- Use server side (301?) redirects for speed, either with nginx or node server
- Log 404's and redirect them to Althea.org home page

deadline:10/26/2018

**Comment by asoltys** [comment]
Copied old blog posts over in this commit: https://github.com/althea-mesh/althea-site-deluxe/commit/6467a5deadaad904c0530d00d30ef32900444710

Crafted this nginx host config that should take care of redirecting everything to the right spot on the new site:

`

    server {
        listen 80 http2;
        listen [::]:80 http2;
        listen 443 ssl http2 default_server;
        listen [::]:443 ssl http2 default_server;
    
        ssl_certificate /etc/letsencrypt/live/altheamesh.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/altheamesh.com/privkey.pem;
    
        server_name .altheamesh.com;
        access_log /var/log/nginx/altheamesh.com-access.log;
        error_log /var/log/nginx/altheamesh.com-error.log;
    
        rewrite ^/blog/(.*)/*$ http://althea.org/blog/$1 permanent;
        rewrite ^/how-it-works/*$ http://althea.org/how-it-works permanent;
        rewrite ^/governance-paper/*$ http://althea.org/whitepaper#governance permanent;
        rewrite ^/network-paper/*$ http://althea.org/whitepaper#network permanent;
        rewrite ^/use-cases/wisp/*$ http://althea.org/case-studies permanent;
        rewrite ^/protocols/*$ http://althea.org/whitepaper permanent;
        rewrite ^/*$ http://althea.org/ permanent;
    
        error_page 404 = @redirect;
        location @redirect {
          return 301 https://althea.org/;
        }
    }

`

You can try it out by temporarily adding these lines to your /etc/hosts file or equivalent:

158.69.192.27 altheamesh.com
158.69.192.27 www.altheamesh.com

Attempted but failed to get a letsencrypt cert using the DNS challenge method so @jkilpatr suggested we switch the domain over first and then use the http challenge method.
