### ISSUE TITLE
New Get Involved

### ISSUE THREAD

**Issue by jtremback** [althea-net/issue-warehouse#18]
- Two main sections, but they should be very simple and clear. Maybe side by side if it looks good. Use Mary's user/organizer images

Use this copy:

# Get Involved

## As an organizer

Set up a test deployment for your building, neighborhood, or city.

| Get Started |

## As a user

We’ll match you with local networks as they become available. 

| Get Connected |

**Comment by asoltys** [comment]
Implemented by https://github.com/althea-mesh/althea-site-deluxe/commit/38df55427f0924a9f6c4ad09a42ae7d95f45f5cd
