### ISSUE TITLE
Images are very zoomed out and hard to see on how it works.

### ISSUE THREAD

**Issue by jtremback** [althea-net/issue-warehouse#24]
RESOLUTION: We will switch to the basic mobile view for now on the desktop site instead of the fade, and zoom each image in to fill the box

This is because they have to fade into each other, which means that the first images looked super zoomed out.

Possible solutions:

- Eliminate the transition effect (already eliminated on tablet and mobile), making it so that there is no more need to avoid changing the zoom level between images.

- Somehow make the effect look like it is zooming out between images without having it be janky

- Full motion video animation (probably not in the short term)

- Some other creative solution on how to display things

**Comment by asoltys** [comment]
Done in https://github.com/althea-mesh/althea-site-deluxe/commit/e88377454c73a4dfdbff9fc27332df18e61e4c0c

The images are all static now. I zoomed in on some of them and made separate versions for the different screen sizes.
